export const START_LOGIN = 'user/START_LOGIN'
export const SUCCESS_LOGIN = 'user/SUCCESS_LOGIN'
export const ERROR_LOGIN = 'user/ERROR_LOGIN'
export const SET_SESSION = 'user/SET_SESSION'
export const SET_ROLE = 'user/SET_ROLE'
