
export const SET_NETWORK_STATUS = 'global/SET_NETWORK_STATUS'
export const SET_TOP_MESSAGE = 'global/SET_TOP_MESSAGE'
export const CLEAR_TOP_MESSAGE = 'global/CLEAR_TOP_MESSAGE'
export const SET_NETWORK_FAILURE = 'global/SET_NETWORK_FAILURE'
export const CLEAR_NETWORK_FAILURE = 'global/CLEAR_NETWORK_FAILURE'
export const CHECK_NETWORK_FAILURE = 'global/CHECK_NETWORK_FAILURE'
